more compiler issues on kickstart side, but my side has no issues
really strange

```
error[E0502]: cannot borrow `*buffer` as mutable because it is also borrowed as immutable
   --> Solution.rs:112:29
    |
106 |             let test_case_sizes: Vec<&str> = buffer.split(' ').collect();
    |                                              ------ immutable borrow occurs here
...
112 |                             buffer.clear();
    |                             ^^^^^^ mutable borrow occurs here
...
128 |         },
    |         - immutable borrow ends here

error[E0502]: cannot borrow `buffer` as mutable because `*buffer` is also borrowed as immutable
   --> Solution.rs:113:88
    |
106 |             let test_case_sizes: Vec<&str> = buffer.split(' ').collect();
    |                                              ------ immutable borrow occurs here
...
113 |                             handle_test_case_scores(num_of_students, num_to_pick, &mut buffer);
    |                                                                                        ^^^^^^ mutable borrow occurs here
...
128 |         },
    |         - immutable borrow ends here

error: aborting due to 2 previous errors

```